# Generated by Django 5.2.3 on 2026-07-23 03:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='Customer name')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='National ID / company registration number')),
                ('customer_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Physical address')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_rep', models.ForeignKey(blank=True, help_text='Sales representative who owns this customer relationship.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('site_assessment', 'Site assessment'), ('quotation', 'Quotation'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('in_progress', 'Installation in progress'), ('commissioned', 'Commissioned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='lead', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
