# Generated by Django 5.2.3 on 2026-07-23 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_customer_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('scheduling_notes', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('roof_type', models.CharField(blank=True, choices=[('flat', 'Flat'), ('pitched', 'Pitched / gable'), ('hip', 'Hip'), ('shed', 'Shed / mono-pitch'), ('other', 'Other')], max_length=20)),
                ('roof_material', models.CharField(blank=True, max_length=100)),
                ('roof_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roof_orientation', models.CharField(blank=True, choices=[('n', 'North'), ('ne', 'North-east'), ('e', 'East'), ('se', 'South-east'), ('s', 'South'), ('sw', 'South-west'), ('w', 'West'), ('nw', 'North-west')], max_length=4)),
                ('roof_tilt_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roof_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor — needs repair')], max_length=20)),
                ('structural_integrity_ok', models.BooleanField(blank=True, null=True)),
                ('structural_notes', models.TextField(blank=True)),
                ('shading_level', models.CharField(blank=True, choices=[('none', 'None'), ('minimal', 'Minimal'), ('moderate', 'Moderate'), ('heavy', 'Heavy')], max_length=20)),
                ('shading_notes', models.TextField(blank=True)),
                ('current_supply_type', models.CharField(blank=True, choices=[('grid_single', 'Grid — single phase'), ('grid_three', 'Grid — three phase'), ('off_grid', 'Off-grid / none'), ('generator', 'Generator backup')], max_length=20)),
                ('electrical_panel_capacity_amps', models.PositiveIntegerField(blank=True, null=True)),
                ('average_monthly_consumption_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('has_existing_backup', models.BooleanField(default=False)),
                ('backup_notes', models.TextField(blank=True)),
                ('available_installation_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roof_access_notes', models.TextField(blank=True)),
                ('recommended_system_size_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assessor_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_conducted', to=settings.AUTH_USER_MODEL)),
                ('assigned_engineer', models.ForeignKey(blank=True, help_text='Site engineer who will conduct the visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_assessments', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_assessment', to='project.project')),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_booked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
