# Generated by Django 5.2.3 on 2026-07-30 03:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_siteassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Mono PERC 450W' or 'Growatt SPF 5000ES'", max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('unit_price_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit price (KES)')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from the sizing calculator and new quotations.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_kwh', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Capacity (kWh)')),
                ('chemistry', models.CharField(choices=[('lithium', 'Lithium (LiFePO4)'), ('lead_acid', 'Lead-acid')], default='lithium', max_length=20)),
                ('usable_depth_of_discharge_percent', models.PositiveIntegerField(default=90, help_text='How much of nameplate capacity is safely usable — typically ~90% for lithium, ~50% for lead-acid.', verbose_name='Usable DoD (%)')),
                ('max_discharge_rate_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Batteries',
                'ordering': ['capacity_kwh', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Mono PERC 450W' or 'Growatt SPF 5000ES'", max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('unit_price_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit price (KES)')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from the sizing calculator and new quotations.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity_kw', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rated output (kW)')),
                ('phase', models.CharField(choices=[('single', 'Single phase'), ('three', 'Three phase')], default='single', max_length=10)),
                ('is_hybrid', models.BooleanField(default=True, help_text='Can charge/discharge a battery bank, not grid-tie only.')),
                ('max_input_voltage', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inverter',
                'ordering': ['capacity_kw', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Mono PERC 450W' or 'Growatt SPF 5000ES'", max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('unit_price_kes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Unit price (KES)')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive items are hidden from the sizing calculator and new quotations.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wattage_w', models.PositiveIntegerField(help_text='Rated power per panel', verbose_name='Wattage (W)')),
                ('panel_area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Physical area of one panel — used to check it will fit the roof.', max_digits=5, null=True, verbose_name='Panel footprint (m²)')),
                ('efficiency_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Solar panel',
                'ordering': ['wattage_w', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to client'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('payment_terms', models.CharField(blank=True, default='80% on order, 20% upon completion.', max_length=255)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True, help_text='Exclusions, assumptions, or anything else the client should know.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_prepared', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('bos', 'Balance of system'), ('services', 'Services'), ('other', 'Other')], default='equipment', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price_kes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='project.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_consumption_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_system_size_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('backup_autonomy_hours', models.PositiveIntegerField(default=0)),
                ('panel_quantity', models.PositiveIntegerField(default=0)),
                ('battery_quantity', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('battery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.battery')),
                ('inverter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.inverter')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='project.solarpanel')),
                ('site_assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='project.siteassessment')),
            ],
        ),
    ]
