# Generated by Django 5.2.3 on 2026-07-30 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_battery_inverter_solarpanel_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrecommendation',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemrecommendation',
            name='review_notes',
            field=models.TextField(blank=True, help_text="Anything adjusted from the calculator's pick, and why."),
        ),
        migrations.AddField(
            model_name='systemrecommendation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemrecommendation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('site_assessment', 'Site assessment'), ('engineer_review', 'Engineer review'), ('quotation', 'Quotation'), ('approved', 'Approved'), ('invoiced', 'Invoiced'), ('in_progress', 'Installation in progress'), ('commissioned', 'Commissioned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='lead', max_length=20),
        ),
    ]
