# Generated by Django 5.2.3 on 2026-09-28 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_systemrecommendation_is_reviewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Roof mounting rails (per set)'", max_length=150)),
                ('unit_price_kes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit price (KES)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from new quotations.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='battery',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='inverter',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='solarpanel',
            name='stock_quantity',
        ),
    ]
