# Generated by Django 5.2.3 on 2026-09-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_productcategory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLoadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lighting', 'Lighting'), ('refrigeration', 'Refrigeration'), ('cooling_heating', 'Cooling / heating'), ('kitchen', 'Kitchen'), ('laundry', 'Laundry'), ('water', 'Water pumping / heating'), ('entertainment_it', 'Entertainment / IT / network'), ('office_pos', 'Office / point of sale'), ('motors_machinery', 'Motors / machinery'), ('security_comms', 'Security / communications'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(help_text="e.g. 'Fridge / freezer'", max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rated_power_w', models.PositiveIntegerField(help_text='Running power of one unit, from its nameplate.', verbose_name='Rated power per unit (W)')),
                ('surge_multiplier', models.DecimalField(decimal_places=1, default=1, help_text='Start-up power as a multiple of running power. 1 for electronics/lighting, 3-6 for motors and compressors.', max_digits=4, verbose_name='Start-up surge (x)')),
                ('hours_per_day', models.DecimalField(decimal_places=1, default=1, help_text='Effective hours at full power per day. For fridges/AC that cycle, use the equivalent full-power hours.', max_digits=4, verbose_name='Hours per day')),
                ('is_essential', models.BooleanField(default=False, help_text='Must keep running when the grid is down — sizes the battery backup.', verbose_name='Keep on during outage')),
                ('is_three_phase', models.BooleanField(default=False, verbose_name='Three-phase')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_items', to='project.siteassessment')),
            ],
            options={
                'ordering': ['category', 'name', 'id'],
            },
        ),
    ]
